name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

env:
  TAG_NAME: pipeline
  VERSION: 0

jobs:
  generate-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: | 
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "main" ]]; then
            tag_name="latest"
            version="dev - $GITHUB_SHA"
          else
            tag_name="$branch"
            version="$branch"
          fi
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Chore
        run: printenv
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change build version
        run: |
          sed -i "s/VERSION_TAG/$VERSION/" main.go
      - name: Build binaries
        run: |
          bash dev/generate-bin.sh
      - name: Delete old release
        uses: dev-drprasad/delete-older-releases@v0.2.1
        continue-on-error: true
        with:
          keep_latest: 0
          delete_tag_pattern: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: bin/

  docker-release:
    name: Generate docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: | 
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "main" ]]; then
            tag_name="latest"
            version="dev - $GITHUB_SHA"
          else
            tag_name="$branch"
            version="$branch"
          fi
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change build version
        run: |
          sed -i "s/VERSION_TAG/$VERSION/" main.go
      # based on: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: CHORE
        run: printenv
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: arielmorelli/servus-api:${{ env.TAG_NAME }}
